In [39]:
from functools import partial, reduce
from math import sqrt
import numpy as np

In [10]:
hwa1 = [175, 68, 40]
hwa2 = [169, 80, 62]
hwa3 = [150, 40, 12]

In [6]:
def vector_union(v1, v2):
    return [v1i + v2i for v1i, v2i in zip(v1, v2)]

vector_union(hwa1, hwa2)

[344, 148, 102]

In [7]:
def vector_subtraction(v1, v2):
    return [v1i - v2i for v1i, v2i in zip(v1, v2)]

vector_subtraction(hwa1, hwa2)

[6, -12, -22]

In [11]:
def vector_sum(vectors):
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_union(result, vector)
    return result

vector_sum([hwa1, hwa2, hwa3])

[494, 188, 114]

In [16]:
def vector_sum(vectors):
    return reduce(vector_union, vectors)

vector_sum([hwa1, hwa2, hwa3])

[494, 188, 114]

In [17]:
def scalar_multiply(v, c):
    return [c * vi for vi in v]

scalar_multiply(hwa1, 10)

[1750, 680, 400]

In [18]:
def vectors_mean(vectors):
    return scalar_multiply(vector_sum(vectors), 1 / len(vectors))

vectors_mean([hwa1, hwa2, hwa3])

[164.66666666666666, 62.666666666666664, 38.0]

In [19]:
def dot(v1, v2):
    return sum(v1i * v2i for v1i, v2i in zip(v1, v2))

dot(hwa1, hwa2)

37495

In [22]:
dot([2, 1], [0.5, 1])

2.0

In [23]:
def sum_of_squares(v):
    return dot(v, v)

sum_of_squares(hwa1)

36849

In [26]:
def length(v):
    return sqrt(sum_of_squares(v))

length(hwa1)

191.96093352554837

In [29]:
def distance(v1, v2):
    return sqrt(sum_of_squares(vector_subtraction(v1, v2)))

distance(hwa1, hwa2)

25.768197453450252

In [38]:
class Vector:
    def __init__(self, values=[]):
        self.vector = values;
        
    def __repr__(self):
        return 'Vector: ' + ', '.join([str(i) for i in self.vector]) 

    def scalar_multiply(self, c):
        self.vector = [c * i for i in self.vector]
        return self


v = Vector([1, 3])
v.scalar_multiply(8)

Vector: 8, 24

In [47]:
ar = np.vectorize(round)(np.random.random((5, 5)), 2)
ar

array([[0.26, 0.51, 0.46, 0.69, 0.47],
       [0.14, 0.75, 0.26, 0.95, 0.23],
       [0.42, 0.93, 0.18, 0.56, 0.57],
       [0.07, 0.17, 0.01, 0.55, 0.03],
       [0.44, 0.02, 0.06, 0.63, 0.18]])

In [48]:
ar[:, 2] # берем третий столбец

array([0.46, 0.26, 0.18, 0.01, 0.06])

In [49]:
ar[1] # берем вторую строку

array([0.14, 0.75, 0.26, 0.95, 0.23])

In [51]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])