In [4]:
def fun(n):
    return ((n + 1) * (5 * n + 4) * (5 * n + 3) * (5 * n + 2) * (5 * n + 1) * (5 * n)) / ((3 * n + 4) ** 2 * (3 * n + 3) ** 2 * (3 * n + 2) ** 2) 

In [9]:
fun(100000000000000000)

4.286694101508917

In [2]:
summ = 0
n = 100001
for i in range(1, n):
    summ += n/(n+3*i)**2
    
summ

0.24999468760234428

In [13]:
import numpy as np 


def f1(x):
    return (x)**(1/3)*(np.sin(1/(2*x-1)))**2


def f2(x):
    return 1 - np.cos(np.pi/x)


def f3(x):
    return np.arctan(x)/(2*x**2-1)


def f4(x):
    return np.log(x)/(3*x-1)


def f5(x):
    return np.e**(1/x)-1

In [14]:
def r(n):
    summ = [0, 0, 0, 0, 0]

    for i in range(1, n):
        summ[0] += f1(i) 
        summ[1] += f2(i)
        summ[2] += f3(i)
        summ[3] += f4(i)
        summ[4] += f5(i)
    
    return summ

In [15]:
r(1000)

[1.0788979524614446,
 4.8657816928256175,
 1.222018929886699,
 8.039043898119056,
 8.562159256612224]

In [16]:
r(100000)

[1.082476643827601,
 4.870669613625852,
 1.222796616765149,
 22.179436385167055,
 13.168319859405651]

In [1]:
import pandas as pd
import numpy as np

In [62]:
data = np.array([[7, 8, 9, 10, 11, 12, 13], [7.4, 8.4, 9.1, 9.4, 9.5, 9.5, 9.4]]).T
summ = np.zeros((3, 4))
data

array([[ 7. ,  7.4],
       [ 8. ,  8.4],
       [ 9. ,  9.1],
       [10. ,  9.4],
       [11. ,  9.5],
       [12. ,  9.5],
       [13. ,  9.4]])

In [63]:
for index, row  in enumerate(data):
    summ[0][0] += 1
    summ[0][1] += row[0] 
    summ[0][2] += row[0] ** 2
    summ[1][0] += row[0]
    summ[1][1] += row[0] ** 2
    summ[1][2] += row[0] ** 3
    summ[2][0] += row[0] ** 2
    summ[2][1] += row[0] ** 3
    summ[2][2] += row[0] ** 4
    summ[0][3] += row[1]
    summ[1][3] += row[0] * row[1]
    summ[2][3] += row[0] ** 2 * row[1]

summ

array([[7.0000e+00, 7.0000e+01, 7.2800e+02, 6.2700e+01],
       [7.0000e+01, 7.2800e+02, 7.8400e+03, 6.3560e+02],
       [7.2800e+02, 7.8400e+03, 8.6996e+04, 6.6834e+03]])

In [64]:
matrix, answers = summ[:, :3], summ[:, 3]
matrix, answers

(array([[7.0000e+00, 7.0000e+01, 7.2800e+02],
        [7.0000e+01, 7.2800e+02, 7.8400e+03],
        [7.2800e+02, 7.8400e+03, 8.6996e+04]]),
 array([  62.7,  635.6, 6683.4]))

In [65]:
np.linalg.solve(matrix, answers)

array([-4.85714286,  2.5452381 , -0.11190476])

In [ ]:
tmp = 0
for i, row in enumerate(data):
    tmp += r[0]+row[0]+row[0]**2-row[1]

In [ ]:
for i, row in enumerate(data):
    